In [1]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel(r"C:\Users\navee\Desktop\DS Projects\DS Projects\02 Data Cleaning\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [3]:
df.shape

(21, 8)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

In [5]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [6]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         20 non-null     int64
 1   First_Name         20 non-null     object
 2   Last_Name          19 non-null     object
 3   Phone_Number       18 non-null     object
 4   Address            20 non-null     object
 5   Paying Customer    20 non-null     object
 6   Do_Not_Contact     16 non-null     object
 7   Not_Useful_Column  20 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

In [8]:
# If you notice we have 20 entries in data. CustomerID, First_Name all 20 "non-null" but Last_Name has 19 "non-null" means there is one null value.
# Similarly for Phone_Number, Do_Not_Contact also has NaN value. Lets make a sum of Nan values in columns.
df.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

In [9]:

df.dropna(inplace=True)

# cheaking stts of null values 
df.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            0
Phone_Number         0
Address              0
Paying Customer      0
Do_Not_Contact       0
Not_Useful_Column    0
dtype: int64

In [10]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [11]:
# show the column 
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [12]:
# Dropping or deleting the irrelevent/Blank column and saving the result in variable "drop_column"
drop_col = df.drop(columns='Not_Useful_Column')
drop_col

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [13]:
# delete multiple columns 
drop_mult = df.drop(columns= ['Address', 'Do_Not_Contact'])
drop_mult

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,Yes,True
1,1002,Abed,Nadir,123/643/9775,No,False
3,1004,Dwight,Schrute,123-543-2345,Yes,True
4,1005,Jon,Snow,876|678|3469,Y,True
5,1006,Ron,Swanson,304-762-2467,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,N,False
9,1010,Peter,Parker,123-545-5421,Yes,True
12,1013,Don,Draper,123-543-2345,Yes,False
13,1014,Leslie,Knope,876|678|3469,Yes,False
14,1015,Toby,Flenderson_,304-762-2467,N,False
15,1016,Ron,Weasley,123-545-5421,No,False
16,1017,Michael,Scott,123/643/9775,Yes,False
18,1019,Creed,Braton,N/a,N/a,True
19,1020,Anakin,Skywalker,876|678|3469,Yes,True

In [14]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [15]:
# check data type
df.dtypes

CustomerID            int64
First_Name           object
Last_Name            object
Phone_Number         object
Address              object
Paying Customer      object
Do_Not_Contact       object
Not_Useful_Column      bool
dtype: object

In [16]:
# change the datatype of CustomerID from  int64 to float
df['CustomerID'] = df['CustomerID'].astype('float')

In [17]:
df.dtypes

CustomerID           float64
First_Name            object
Last_Name             object
Phone_Number          object
Address               object
Paying Customer       object
Do_Not_Contact        object
Not_Useful_Column       bool
dtype: object

In [18]:
df.head(3)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True

In [19]:
# Rename Column Names such as "Phone_Number to Contact_Number" / "Do_Not_Contact to Block_Contact"
df = df.rename(columns={'Phone_Number':'Contact_Number', 'Do_Not_Contact':'Block_Contact'})
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
7,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
18,1019.0,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [20]:
# make lowercase of first_name column in dataset 
df['First_Name'].str.lower()

0        frodo
1         abed
3       dwight
4          jon
5          ron
7     sherlock
9        peter
12         don
13      leslie
14        toby
15         ron
16    michael
18       creed
19      anakin
Name: First_Name, dtype: object

In [21]:
# make uppercase of 'Address' column in dataset
df['Address'].str.upper()

0                     123 SHIRE LANE, SHIRE
1                       93 WEST MAIN STREET
3     980 PAPER AVENUE, PENNSYLVANIA, 18503
4                          123 DRAGONS ROAD
5                          768 CITY PARKWAY
7                             98 CLUE DRIVE
9                25TH MAIN STREET, NEW YORK
12                         2039 MAIN STREET
13                         343 CITY PARKWAY
14                            214 HR AVENUE
15                     2395 HOGWARTS AVENUE
16           121 PAPER AVENUE, PENNSYLVANIA
18                                      N/A
19              910 TATOOINE ROAD, TATOOINE
Name: Address, dtype: object

In [22]:
# setting prticular column as index
df.set_index('CustomerID')

,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
CustomerID,,,,,,,
1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
1019.0,Creed,Braton,N/a,N/a,N/a,Yes,True
1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [23]:
# Remove CustomerID column as index
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
3,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
12,1019.0,Creed,Braton,N/a,N/a,N/a,Yes,True
13,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [24]:
# Now Lets clean the rows data starting from First_Name and Last_Name. Clean all the special characters and spaces from both columns.
df['First_Name'] = df['First_Name'].str.replace('/','')
df['Last_Name'] = df['Last_Name'].str.replace('/','')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
3,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
12,1019.0,Creed,Braton,N/a,N/a,N/a,Yes,True
13,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [25]:
# Fix: The error "ValueError: invalid literal for int() with base 10: '123-545-5421'" occurred because the column contains non-numeric characters.
# We will remove the non-numeric characters and then convert the column to a numeric type that can handle missing values.
df['Contact_Number'] = df['Contact_Number'].str.replace('[^0-9]', '', regex=True)
df['Contact_Number'] = pd.to_numeric(df['Contact_Number'], errors='coerce').astype('Int64')
df.dtypes

CustomerID           float64
First_Name            object
Last_Name             object
Contact_Number         Int64
Address               object
Paying Customer       object
Block_Contact         object
Not_Useful_Column       bool
dtype: object

In [29]:
# Remove all the special characters "/,|"" from Contact_Number.
df["Contact_Number"] = df["Contact_Number"].astype(str).str.replace(r'[^0-9-]', '', regex=True)
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
3,1005.0,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
7,1013.0,Don,Draper,1235432345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,3047622467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
12,1019.0,Creed,Braton,,N/a,N/a,Yes,True
13,1020.0,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [32]:
# In column contact number add "-" after every 3 numbers.
df['Contact_Number'] = df['Contact_Number'].str[:3] +'-'+ df['Contact_Number'].str[3:6] + '-' + df['Contact_Number'].str[6:]
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
12,1019.0,Creed,Braton,--,N/a,N/a,Yes,True
13,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [33]:
# In column Contact_Number remove "--".
df['Contact_Number']=df['Contact_Number'].str.replace('--','')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
12,1019.0,Creed,Braton,,N/a,N/a,Yes,True
13,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [34]:
# In Column Address remove all "," and replace with ''.
df['Address'] = df['Address'].str.replace(',', '')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,123 Shire Lane Shire,Yes,No,True
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,980 Paper Avenue Pennsylvania 18503,Yes,Y,True
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,25th Main Street New York,Yes,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,123-643-9775,121 Paper Avenue Pennsylvania,Yes,No,False
12,1019.0,Creed,Braton,,N/a,N/a,Yes,True
13,1020.0,Anakin,Skywalker,876-678-3469,910 Tatooine Road Tatooine,Yes,N,True

In [36]:
# In Column Address remove all "N/a" and replace with ''.
df['Address'] = df['Address'].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,123 Shire Lane Shire,Yes,No,True
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,980 Paper Avenue Pennsylvania 18503,Yes,Y,True
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,25th Main Street New York,Yes,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
11,1017.0,Michael,Scott,123-643-9775,121 Paper Avenue Pennsylvania,Yes,No,False
12,1019.0,Creed,Braton,,,N/a,Yes,True
13,1020.0,Anakin,Skywalker,876-678-3469,910 Tatooine Road Tatooine,Yes,N,True

In [39]:
# From Columns "Paying Customer" find data with "Yes" and replace with "Y" and "No" with "N"
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes','Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No','N')
df['Paying Customer'] = df['Paying Customer'].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,123 Shire Lane Shire,Y,No,True
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,False
2,1004.0,Dwight,Schrute,123-543-2345,980 Paper Avenue Pennsylvania 18503,Y,Y,True
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,True
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
6,1010.0,Peter,Parker,123-545-5421,25th Main Street New York,Y,No,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
11,1017.0,Michael,Scott,123-643-9775,121 Paper Avenue Pennsylvania,Y,No,False
12,1019.0,Creed,Braton,,,,Yes,True
13,1020.0,Anakin,Skywalker,876-678-3469,910 Tatooine Road Tatooine,Y,N,True

In [40]:
# From Columns "Block_Contact" find data with "Yes" and replace with "Y" and "No" with "N"
df['Block_Contact'] = df['Block_Contact'].str.replace('Yes','Y')
df['Block_Contact'] = df['Block_Contact'].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,123 Shire Lane Shire,Y,N,True
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False
2,1004.0,Dwight,Schrute,123-543-2345,980 Paper Avenue Pennsylvania 18503,Y,Y,True
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
6,1010.0,Peter,Parker,123-545-5421,25th Main Street New York,Y,N,True
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,False
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
11,1017.0,Michael,Scott,123-643-9775,121 Paper Avenue Pennsylvania,Y,N,False
12,1019.0,Creed,Braton,,,,Y,True
13,1020.0,Anakin,Skywalker,876-678-3469,910 Tatooine Road Tatooine,Y,N,True

In [41]:
# From Columns "Not_Useful_Column" find data with "True" and replace with "T" and "False" with "F"
# Fix: The error "AttributeError: Can only use .str accessor with string values!" occurred because the column is not of string data type.
# We will convert the column to string data type before applying the replace method.

In [42]:
df['Not_Useful_Column'].dtype

dtype('bool')

In [44]:
df['Not_Useful_Column'] = df['Not_Useful_Column'].astype(str).str.replace('True' , 'T')
df['Not_Useful_Column'] = df['Not_Useful_Column'].astype(str).str.replace('False' , 'F')
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,123 Shire Lane Shire,Y,N,T
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,f
2,1004.0,Dwight,Schrute,123-543-2345,980 Paper Avenue Pennsylvania 18503,Y,Y,T
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,T
4,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,T
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,f
6,1010.0,Peter,Parker,123-545-5421,25th Main Street New York,Y,N,T
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,f
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,f
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,f
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,f
11,1017.0,Michael,Scott,123-643-9775,121 Paper Avenue Pennsylvania,Y,N,f
12,1019.0,Creed,Braton,,,,Y,T
13,1020.0,Anakin,Skywalker,876-678-3469,910 Tatooine Road Tatooine,Y,N,T

In [47]:
# In column "Block_Contact", display only results with "N"
for x in df.index:
    if df.loc[x, 'Block_Contact'] == 'Y':
        df.drop(x, inplace=True)
df

,CustomerID,First_Name,Last_Name,Contact_Number,Address,Paying Customer,Block_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,123 Shire Lane Shire,Y,N,T
3,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,T
5,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,f
6,1010.0,Peter,Parker,123-545-5421,25th Main Street New York,Y,N,T
7,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,f
8,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,f
9,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,f
10,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,f
11,1017.0,Michael,Scott,123-643-9775,121 Paper Avenue Pennsylvania,Y,N,f
13,1020.0,Anakin,Skywalker,876-678-3469,910 Tatooine Road Tatooine,Y,N,T

In [49]:
df.to_excel("customers_cleaned.xlsx", index=False)

In [50]:
import os
print(os.getcwd())

C:\Users\navee\Desktop\learning ds\Step 2 pndas