In [2]:
import pandas as pd

In [4]:
data = pd.read_csv(r"C:\Users\User\Desktop\Projects series\csv data sets\Weather data set.csv")

In [5]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

## How to analyze Dataframe

In [5]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

### .Shape
- it shows total no of ros and columns in dataframe

In [16]:
data.shape

(8784, 8)

### .index
- the attribute provides the index of dataframe

In [17]:
data.index

RangeIndex(start=0, stop=8784, step=1)

### .columns
- it shows the the name of each column

In [18]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [19]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

### .unique()
- When you want to see what the distinct values actually are. . it can be applied on a single solumn as well as on whole dataframe

In [20]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

### .nunique()
- Returns the count of unique values. it is used When you only need to know how many unique values exist.

In [21]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

### . count()
- it shows the total no of non null in each column. it can be applied on single column as wel as whole dataframe

In [22]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

## .value_counts
- counts how many times each unique value appears it can be applied on single column only and
- Returns results sorted in descending order by default

In [23]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

In [24]:
# this parameter normalize=True → Get proportions (percentages)
data['Weather'].value_counts(normalize= True )

Weather
Mainly Clear                               0.239754
Mostly Cloudy                              0.235542
Cloudy                                     0.196721
Clear                                      0.150956
Snow                                       0.044399
Rain                                       0.034836
Rain Showers                               0.021403
Fog                                        0.017077
Rain,Fog                                   0.013206
Drizzle,Fog                                0.009107
Snow Showers                               0.006831
Drizzle                                    0.004668
Snow,Fog                                   0.004212
Snow,Blowing Snow                          0.002163
Rain,Snow                                  0.002049
Thunderstorms,Rain Showers                 0.001821
Haze                                       0.001821
Drizzle,Snow,Fog                           0.001708
Freezing Rain                              0.001594
Freezing Drizzle,Snow                      0.001252
Freezing Drizzle                           0.000797
Freezing Drizzle,Fog                       0.000683
Snow,Ice Pellets                           0.000683
Snow,Haze                                  0.000569
Freezing Rain,Fog                          0.000455
Moderate Snow                              0.000455
Rain,Snow,Ice Pellets                      0.000455
Freezing Fog                               0.000455
Snow Showers,Fog                           0.000455
Thunderstorms,Rain Showers,Fog             0.000342
Thunderstorms,Rain                         0.000342
Freezing Drizzle,Haze                      0.000342
Rain,Haze                                  0.000342
Drizzle,Snow                               0.000228
Moderate Snow,Blowing Snow                 0.000228
Thunderstorms                              0.000228
Freezing Rain,Haze                         0.000228
Rain Showers,Snow Showers                  0.000228
Freezing Rain,Snow Grains                  0.000114
Thunderstorms,Heavy Rain Showers           0.000114
Thunderstorms,Moderate Rain Showers,Fog    0.000114
Thunderstorms,Rain,Fog                     0.000114
Freezing Rain,Ice Pellets,Fog              0.000114
Moderate Rain,Fog                          0.000114
Rain,Snow,Fog                              0.000114
Snow Pellets                               0.000114
Rain Showers,Fog                           0.000114
Drizzle,Ice Pellets,Fog                    0.000114
Rain,Ice Pellets                           0.000114
Rain,Snow Grains                           0.000114
Name: proportion, dtype: float64

In [25]:
# This parameter ascending=True → Sort counts in ascending order
data['Weather'].value_counts(ascending = True)

Weather
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Drizzle,Ice Pellets,Fog                       1
Rain,Snow,Fog                                 1
Rain Showers,Fog                              1
Snow Pellets                                  1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Thunderstorms,Rain,Fog                        1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms,Rain Showers,Fog                3
Rain,Haze                                     3
Freezing Drizzle,Haze                         3
Thunderstorms,Rain                            3
Rain,Snow,Ice Pellets                         4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Freezing Fog                                  4
Snow Showers,Fog                              4
Snow,Haze                                     5
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Freezing Drizzle                              7
Freezing Drizzle,Snow                        11
Freezing Rain                                14
Drizzle,Snow,Fog                             15
Haze                                         16
Thunderstorms,Rain Showers                   16
Rain,Snow                                    18
Snow,Blowing Snow                            19
Snow,Fog                                     37
Drizzle                                      41
Snow Showers                                 60
Drizzle,Fog                                  80
Rain,Fog                                    116
Fog                                         150
Rain Showers                                188
Rain                                        306
Snow                                        390
Clear                                      1326
Cloudy                                     1728
Mostly Cloudy                              2069
Mainly Clear                               2106
Name: count, dtype: int64

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

__________

# Q1 : Find the unique 'wind speed' values in the data and show all

In [27]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [28]:
data['Wind Speed_km/h'].nunique()

34

In [29]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

## Q2 : Find the number of times when the "Weather is exactly clear"

In [30]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [31]:
# Value.counts()
data.Weather.value_counts(ascending = True)

Weather
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Drizzle,Ice Pellets,Fog                       1
Rain,Snow,Fog                                 1
Rain Showers,Fog                              1
Snow Pellets                                  1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Thunderstorms,Rain,Fog                        1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms,Rain Showers,Fog                3
Rain,Haze                                     3
Freezing Drizzle,Haze                         3
Thunderstorms,Rain                            3
Rain,Snow,Ice Pellets                         4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Freezing Fog                                  4
Snow Showers,Fog                              4
Snow,Haze                                     5
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Freezing Drizzle                              7
Freezing Drizzle,Snow                        11
Freezing Rain                                14
Drizzle,Snow,Fog                             15
Haze                                         16
Thunderstorms,Rain Showers                   16
Rain,Snow                                    18
Snow,Blowing Snow                            19
Snow,Fog                                     37
Drizzle                                      41
Snow Showers                                 60
Drizzle,Fog                                  80
Rain,Fog                                    116
Fog                                         150
Rain Showers                                188
Rain                                        306
Snow                                        390
Clear                                      1326
Cloudy                                     1728
Mostly Cloudy                              2069
Mainly Clear                               2106
Name: count, dtype: int64

In [16]:
# filtering 
data[data['Weather Condition'] == 'Clear']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [33]:
# groupby()
data.groupby('Weather').get_group('Clear')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

## Q3: Find the number of times when wind speed was exactly 4km/h

In [34]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [35]:
data[data['Wind Speed_km/h'] ==4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

## Q4: Find out all the Null Values

In [36]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [9]:
data.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

## Q4: Rename the column name Weather of the dataframe to 'Weather Condition'

In [6]:
data.rename(columns={'Weather': 'Weather Condition'}, inplace= True)

In [7]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

## Q: What is mean Visibility

In [8]:
data.Visibility_km.mean()

np.float64(27.664446721311478)

## Q: What is standerd Deviation of presure In this data?

In [9]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [10]:
data['Press_kPa'].std()

0.8440047459486474

## Q: what is variance of 'Relative Humidity ' in this data ?

In [48]:
data['Rel Hum_%'].var()

286.2485501984998

## Q: find the all instances when SNOW was recorded ?
- We can fin this by 3 methods
- values_counts()
- filtering()
- .str.contains()

In [11]:
data.head(1)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog

In [12]:
data['Weather Condition'].value_counts()

Weather Condition
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

In [13]:
data[data['Weather Condition'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [20]:
data[data['Weather Condition'].str.contains('Snow')]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

## Q: Find all instances when 'Wind scope is above 24' and 'visibility is 25'

In [21]:
data.head(1)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog

In [26]:
data[(data['Wind Speed_km/h'] > 24) & (data['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

## Q: What is Minimum and Maximum value of each column against each weather condition

In [ ]:
data.groupby()